apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  ports:
    - name: "8090"
      port: 8092
      targetPort: 8090
  selector:
    app: user-api
  clusterIP: 10.107.154.32
  type: LoadBalancer